In [1]:
import torch


In [3]:
my_tensor = torch.tensor([[1,2,3], [4,5,6]], dtype = torch.float32, requires_grad=  True)

In [9]:
x = torch.zeros(size = (3,3))

In [10]:
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [18]:
x = torch.arange(start = 0.1, end = 1, step = 1)

In [20]:
tensor = torch.arange(4)

In [27]:
#how to convert a numpy array to tensor.
import numpy as np
np_array = np.zeros((5,5))
print(np_array)
np_array = torch.from_numpy(np_array)
print(np_array)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)


In [28]:
#mathematical operations...
x = torch.tensor([1,2,3])
y = torch.tensor([9, 8, 7])

In [29]:
z = x + y

In [31]:
t = torch.zeros(3)
t.add_(x)
print(x)

tensor([1, 2, 3])


In [32]:
z = x.pow(2)

In [33]:
print(z)

tensor([1, 4, 9])


In [34]:
batch = 32
n = 10
m = 20
p = 30

tensor1 = torch.rand((batch, n, m))
tensor2 = torch.rand((batch, m, p))
out_bmm = torch.bmm(tensor1, tensor2)

In [36]:
print(out_bmm.shape)

torch.Size([32, 10, 30])


In [37]:
x1 = torch.rand((5, 5))
x2 = torch.rand((1,5))
z = x1 - x2

In [45]:
x = torch.tensor([[1,2,4],[2,4,5],[2,5,1]])
sum_x = torch.sum(x, dim=0)
values, indices = torch.max(x, dim = 1)
sortedy, indices = torch.sort(x, dim = 0, descending=False)
print(sortedy, indices)

tensor([[1, 2, 1],
        [2, 4, 4],
        [2, 5, 5]]) tensor([[0, 0, 2],
        [1, 1, 0],
        [2, 2, 1]])


In [46]:
#indexing in tensors:

In [47]:
batchsize = 10
features = 25
x = torch.rand((batchsize, features))

In [53]:
x = torch.arange(10)
indices = [2, 5, 8]
print(x[indices])
x = torch.rand((3,5))
print(x)

tensor([2, 5, 8])
tensor([[0.1898, 0.7302, 0.1103, 0.0183, 0.8267],
        [0.7055, 0.9549, 0.8561, 0.7419, 0.0846],
        [0.7335, 0.8260, 0.6851, 0.3288, 0.3920]])


In [56]:
rows = torch.tensor([1,0])
cols = torch.tensor([4,0])
x = torch.arange(10)
print(x[(x>2) & (x < 8)])

tensor([3, 4, 5, 6, 7])


In [62]:
x = torch.arange(9)
x_3v3 = x.view(3,3)
x_3v3 = x.reshape(3,3)

In [63]:
x_3v3 = x_3v3.t()
print(x_3v3)


tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])
